language: go

dist: jammy

go:
- 1.20.x
- 1.21.x
- 1.22.x


notifications:
  email: true

env:
  global:
    - GO111MODULE=on

before_install:
  - sudo apt-get update
  - python -V
  - pyenv global 3.8
  #- '[ "${TRAVIS_PULL_REQUEST}" == "false" ] && openssl aes-256-cbc -K $my_key -iv $my_iv -in myservice.env.enc -out myservice.env -d || true'

install:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.56.2
  - curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

script:
  - make travis-ci

# To enable semantic-release, uncomment these sections.
before_deploy:
  - nvm install 18
  - node --version
  - npm --version
  - npm install
  - pip install --user bump2version

deploy:
  - provider: script
    script: npm run semantic-release
    skip_cleanup: true
    on:
      go: '1.20.x'
      branch: main
